version: "3"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./postgres-data/:/data/postgres
    ports:
      - ${POSTGRES_PORT-5432}:5432
    networks:
      - bud-comments


  comments-microservice:
    build: .
    ports:
      - 3001:3000
    links:
      - postgres
    networks:
      - bud-rabbitmq
      - bud-comments
    environment:
      PORT: 3000
      RABBITMQ_CONNECTION_STRING: amqp://rabbitmq:5672
      DATABASE_URL: postgresql://comments:changeme@postgres:5432/comments?schema=public
      AUTHZ_ISSUER: 'https://dev-0qjqjqjq.auth0.com/'


networks:
  bud-rabbitmq:
    external: true
  bud-comments: